models.py
from datetime import datetime
import re

from app import db

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.column(db.String(140))
    slug = db.column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *arghs, **kwargs):
        super().__init___(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from config import Config
from content.blueprint import content
from content.blueprint import static

app = Flask(__name__)
app.config.from_object(Config)

app.register_blueprint(content, url_prefix='/content')
# localhost:5050/content

app.register_blueprint(static, url_prefix='/static')
# localhost:5050/static

db = SQLAlchemy(app)

content/blueprint.py
from flask import Blueprint
from flask import render_template

content = Blueprint('content', __name__, template_folder='templates')

# localhost:5050/content/mediapack
@content.route('/mediapack')
def content_list_mediapack():
    return render_template('content/mediapack.html')

# localhost:5050/content/forms
@content.route('/forms')
def content_list_forms():
    return render_template('content/forms.html')

# localhost:5050/content/projectvideos
@content.route('/projectvideos')
def content_list_projectvideos():
    return render_template('content/projectvideos.html')

# localhost:5050/content/annualreports
@content.route('/annualreports')
def content_list_annualreports():
    return render_template('content/annualreports.html')

# localhost:5050/content/articlelinks
@content.route('/articlelinks')
def content_list_articlelinks():
    return render_template('content/articlelinks.html')

static = Blueprint('static', __name__, template_folder='templates')

# localhost:5050/static/donations
@static.route('/donations')
def static_list_donations():
    return render_template('static/donations.html')

# localhost:5050/static/contact
@static.route('/contact')
def static_list_contact():
    return render_template('static/contact.html')

main.py
from app import app
from app import db
import views

if __name__ == '__main__':
    app.run(port=5050)

views.py
from flask import render_template

from app import app


@app.route('/')
def index():
    return render_template('index.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link href="{{url_for('static',filename='css/main.css')}}" rel="stylesheet">
</head>

<body>
    <div class="container mx-auto">
        <nav class="bg-white border-gray-200 dark:border-gray-600 dark:bg-gray-900">
            <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl p-4">
                <a href={{ url_for('index') }} class="flex items-center">
                    <img src="https://flowbite.com/docs/images/logo.svg" class="h-8 mr-3" alt="Flowbite Logo" />
                    <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
                </a>
                <button data-collapse-toggle="mega-menu-full" type="button"
                    class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                    aria-controls="mega-menu-full" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                            clip-rule="evenodd"></path>
                    </svg>
                </button>
                <div id="mega-menu-full"
                    class="items-center justify-between font-medium hidden w-full md:flex md:w-auto md:order-1">
                    <ul
                        class="flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                        <li>
                            <button aria-expanded="false" id="mega-menu-full-dropdown-button"
                                data-collapse-toggle="mega-menu-full-dropdown"
                                class="flex items-center justify-between w-full py-2 pl-3 pr-4  text-gray-900 rounded md:w-auto hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700">Media
                                & Press
                                <svg class="w-5 h-5 ml-1" fill="currentColor" viewBox="0 0 20 20"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                        clip-rule="evenodd"></path>
                                </svg></button>
                        </li>
                        <li>
                            <a href="{{ url_for('static.static_list_donations')}}"
                                class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700">Donations</a>
                        </li>
                        <li>
                            <a href="{{ url_for('static.static_list_contact')}}"
                                class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div id="mega-menu-full-dropdown"
                class="mt-1 border-gray-200 shadow-sm bg-gray-50 md:bg-white border-y dark:bg-gray-800 dark:border-gray-600">
                <div
                    class="grid max-w-screen-xl px-4 py-5 mx-auto text-gray-900 dark:text-white sm:grid-cols-2 md:px-6">
                    <ul>
                        <li>
                            <a href="{{ url_for('content.content_list_mediapack')}}"
                                class="block p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
                                <div class="font-semibold">Media Pack</div>
                                <span class="text-sm text-gray-500 dark:text-gray-400">Manuals to Whitepapers. All
                                    digital document available for download.</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('content.content_list_forms')}}" class="block p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
                                <div class="font-semibold">Forms</div>
                                <span class="text-sm text-gray-500 dark:text-gray-400">Forms available to download in
                                    digital format.</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('content.content_list_projectvideos')}}" class="block p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
                                <div class="font-semibold">Project Videos</div>
                                <span class="text-sm text-gray-500 dark:text-gray-400">Watch our project videos for insights into our work and process.</span>
                            </a>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <a href="{{ url_for('content.content_list_annualreports')}}" class="block p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
                                <div class="font-semibold">Annual Reports</div>
                                <span class="text-sm text-gray-500 dark:text-gray-400">Get instant access to our Annual
                                    Reports in digital format.</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('content.content_list_articlelinks')}}" class="block p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
                                <div class="font-semibold">Article Links</div>
                                <span class="text-sm text-gray-500 dark:text-gray-400">Stay up-to-date with our relevant
                                    and informative article links.</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <section class="flex justify-center items-center">
            {% block content %}

            {% endblock %}
        </section>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index Page
{% endblock %}

{% block content %}
    <h1>Hello from index page</h1>
{% endblock %}